##Basic Vector and Matrix Operation with Numpy.

#Problem1: Array Creation

In [2]:
import numpy as np

#1 Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

#2 Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("All-ones 4x2 array:\n", ones_array)

#3 Return a new array of given shape and type, filled with a fill value
filled_array = np.full((3, 3), 7)
print("3x3 array filled with 7:\n", filled_array)

#4 Return a new array of zeros with the same shape and type as a given array
sample_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(sample_array)
print("Zeros array with same shape and type as sample_array:\n", zeros_like_array)

#5 Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("Ones array with same shape and type as sample_array:\n", ones_like_array)

#6 Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Empty 2x2 array:
 [[2.39852522e-316 0.00000000e+000]
 [1.58101007e-322 4.23274456e+175]]
All-ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros array with same shape and type as sample_array:
 [[0 0]
 [0 0]]
Ones array with same shape and type as sample_array:
 [[1 1]
 [1 1]]
Numpy array from list:
 [1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [3]:
import numpy as np

#1 Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_10_to_49)

#2 Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

#3 Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

#4 Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

#5 Create a 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#6 Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)

#7 Reverse an array `arr = [1, 2, 0, 0, 4, 0]`
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

#8 Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on the border and 0 inside:\n", border_array)

#9 Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30:
 [0.07926051 0.08857749 0.17641279 0.54311586 0.75556897 0.62354469
 0.70925143 0.5029167  0.37754223 0.34968662 0.5120427  0.59299829
 0.40980052 0.74404521 0.90176915 0.66812827 0.38654064 0.22520607
 0.13447091 0.12393946 0.62782779 0.8199222  0.04999    0.26210986
 0.57868193 0.60326102 0.2093275  0.3128108  0.01481929 0.84970192]
Mean of the array: 0.44110902759118625
10x10 random array:
 [[0.69244065 0.63421221 0.13557933 0.97195463 0.0066251  0.84757083
  0.6372717  0.23849597 0.81099147 0.83580238]
 [0.45392223 0.67349747 0.97208588 0.48419009 0.40995998 0.14006421
  0.00854861 0.53852591 0.03182468 0.03799799]
 [0.4741251  0.33325431 0.95317895 0.60111192 0.26772364 0.86619607

#Problem - 3: Array Operations:

In [4]:
#import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("Addition of x and y:\n", add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)

# 3. Multiply the array with any integer
multiply_result = x * 3
print("Multiplication of x by 3:\n", multiply_result)

# 4. Find the square of each element of the array
square_result = x**2
print("Square of each element of x:\n", square_result)

# 5. Find the dot product
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows, and v and w along columns
concatenate_rows = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concatenate_rows)

concatenate_columns = np.vstack((v, w)).T
print("Concatenation of v and w along columns:\n", concatenate_columns)

# 7. Concatenate x and v
try:
    concatenate_xv = np.concatenate((x, v))
    print("Concatenation of x and v:\n", concatenate_xv)
except ValueError as e:
    print("Error:", e)
    print("Explanation: x is a 2D array with shape (2, 2), and v is a 1D array with shape (2,). Their dimensions do not match for concatenation.")

Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]
Square of each element of x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array with shape (2, 2), and v is a 1D array with shape (2,). Their dimensions do not match for concatenation.


#Problem - 4: Matrix Operations:

In [7]:
#import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^{-1} = I
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
identity_matrix = np.eye(2)
print("A * A^{-1}:\n", result)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
AB_transpose = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", BT_AT)

# Solve the system of linear equations using inverse method
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution using inverse method:\n", X)

# Solve the system of linear equations using np.linalg.solve
X_solve = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:\n", X_solve)

A * A^{-1}:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Solution using inverse method:
 [[ 2.]
 [ 1.]
 [-2.]]
Solution using np.linalg.solve:
 [[ 2.]
 [ 1.]
 [-2.]]


##Experiment: How Fast is Numpy?

#1. Element-wise Addition:

In [9]:
import time
import numpy as np

# Size of the arrays
size = 1000000

# Create two Python lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Element-wise addition using Python lists
start_time = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise addition using Python lists: {list_time:.6f} seconds")

# Element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise addition using NumPy arrays: {array_time:.6f} seconds")

Time taken for element-wise addition using Python lists: 0.070663 seconds
Time taken for element-wise addition using NumPy arrays: 0.007126 seconds


#2. Element-wise Multiplication

In [10]:
import time
import numpy as np

# Size of the arrays
size = 1000000

# Create two Python lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Element-wise multiplication using Python lists
start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Python lists: {list_time:.6f} seconds")

# Element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise multiplication using NumPy arrays: {array_time:.6f} seconds")


Time taken for element-wise multiplication using Python lists: 0.154427 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.005377 seconds


#3. Dot Product

In [11]:
import time
import numpy as np

# Size of the arrays
size = 1000000

# Create two Python lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Dot product using Python lists
start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for dot product using Python lists: {list_time:.6f} seconds")

# Dot product using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for dot product using NumPy arrays: {array_time:.6f} seconds")


Time taken for dot product using Python lists: 0.133593 seconds
Time taken for dot product using NumPy arrays: 0.002124 seconds


#Matrix Multiplication

In [12]:
import time
import numpy as np

# Size of the matrices
size = 1000

# Create two Python lists (matrices)
list1 = [[i + j for j in range(size)] for i in range(size)]
list2 = [[i + j for j in range(size)] for i in range(size)]

# Create two NumPy arrays (matrices)
array1 = np.array(list1)
array2 = np.array(list2)

# Matrix multiplication using Python lists
def matrix_multiply_python(A, B):
    result = [[0 for _ in range(size)] for _ in range(size)]
    for i in range(size):
        for j in range(size):
            for k in range(size):
                result[i][j] += A[i][k] * B[k][j]
    return result

start_time = time.time()
result_list = matrix_multiply_python(list1, list2)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python lists: {list_time:.6f} seconds")

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy arrays: {array_time:.6f} seconds")


Time taken for matrix multiplication using Python lists: 236.575397 seconds
Time taken for matrix multiplication using NumPy arrays: 2.153225 seconds
